tls:
  certificates:
    - certFile: '/etc/traefik/certs/local/localhost.pem'
      keyFile: '/etc/traefik/certs/local/localhost-key.pem'

  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      curvePreferences:
        - X25519
        - CurveP521
        - CurveP384
